### ISSUE TITLE
TypeError: GherkinWrapper.forPlaywright is not a constructor

### ISSUE THREAD

**Issue by tjmcewan** [Niitch/gherkin-wrapper#2]
Trying to follow the example in an existing project and not having much luck.

```
TypeError: GherkinWrapper.forPlaywright is not a constructor

   at features/steps/simple.spec.ts:11

   9 | });
  10 |
> 11 | const wrapper = new GherkinWrapper.forPlaywright(test);
     |                 ^
  12 | wrapper.forPlaywright(test);
  13 |
  14 | wrapper.when("the Maker starts a game", () => null);
```

Here's our `tsconfig.json` in case it helps:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/utils/theme.js"],
  "exclude": ["node_modules"]
}
```

**Comment by Niitch** [comment]
Given the issue #3 you created, I assume you resolved this problem.

There was an import error in the version 0.1.0 that has been fixed.

Was that the issue or did you found something else?

**Comment by tjmcewan** [comment]
Sadly not resolved.  I made the other repo to test it in isolation.  It's seemingly a conflict with our specific setup but I can't share the repo it's in.
